version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/docs_requirements.txt
      # Install Lizzy
    - method: pip
      path: .


sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false